/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Dao.ServiceDao;
import Entities.Service;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author AZIZ
 */
public class afficservice extends javax.swing.JFrame {

    int selected = 0;
    List<Service> services;

    /**
     * Creates new form afficservice
     */
    public afficservice() {
        initComponents();
        afficherService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        desc1 = new javax.swing.JTextArea();
        desc2 = new javax.swing.JTextArea();
        desc3 = new javax.swing.JTextArea();
        tit1 = new javax.swing.JLabel();
        tit2 = new javax.swing.JLabel();
        tit3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vd = new javax.swing.JButton();
        vg = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 300, 200));
        getContentPane().add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 300, 200));
        getContentPane().add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, 300, 200));

        desc1.setColumns(20);
        desc1.setRows(5);
        desc1.setMaximumSize(new java.awt.Dimension(164, 94));
        desc1.setMinimumSize(new java.awt.Dimension(164, 94));
        getContentPane().add(desc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 494, 300, 110));

        desc2.setColumns(20);
        desc2.setRows(5);
        getContentPane().add(desc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, -1, -1));

        desc3.setColumns(20);
        desc3.setRows(5);
        getContentPane().add(desc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 510, -1, -1));
        getContentPane().add(tit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 120, 30));
        getContentPane().add(tit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 120, 30));
        getContentPane().add(tit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 460, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/serviceee.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 370, 430));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/serviceee.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, 370, 430));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/serviceee.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 370, 430));

        vd.setText("jButton1");
        vd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vdActionPerformed(evt);
            }
        });
        getContentPane().add(vd, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 640, 50, -1));

        vg.setText("jButton2");
        vg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vgActionPerformed(evt);
            }
        });
        getContentPane().add(vg, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 640, 50, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userble.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 100, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btacceuilbleu.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btproduitbleu.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btservbleu.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btventeblanc.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blcontblan.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 60, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shopping-cart.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 60, -1, 50));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 130, 30));

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 130, 30));

        jButton2.setText("jButton2");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 130, 30));

        jButton3.setText("jButton3");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 180, -1));

        jButton4.setText("jButton4");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 70, 110, 30));

        jButton5.setText("jButton5");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 80, 20, 10));

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 50, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/acceuil.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vdActionPerformed
        // TODO add your handling code here:

        if (selected < services.size()-3) {
            selected++;
        }
        afficherService();
    }//GEN-LAST:event_vdActionPerformed

    private void vgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vgActionPerformed
        // TODO add your handling code here:
        if (selected > 0) {
            selected --;
        }
        afficherService();
    }//GEN-LAST:event_vgActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        AjouterProduit md = new AjouterProduit();
        md.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        homep p = new homep();
        p.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Produit pr = new Produit();
        pr.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void afficherService() {

        ServiceDao pd = new ServiceDao();
        services = pd.findAll();
        Service p = services.get(selected);
        try {
File sourceimage = new File(
            LoginInfo.cwamp+LoginInfo.localhost+p.getImgServ());
            Image image = ImageIO.read(sourceimage).getScaledInstance(300, 200, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(image);

            img1.setIcon(icon);

        } catch (IOException ex) {
            Logger.getLogger(afficservice.class.getName()).log(Level.SEVERE, null, ex);
        }
        tit1.setText(p.getTitre());
        desc1.setText(p.getDescription());      
        p = services.get(selected + 1);
        try {
            File sourceimage = new File(
                    LoginInfo.cwamp + LoginInfo.localhost + p.getImgServ());
            Image image = ImageIO.read(sourceimage).getScaledInstance(300, 200, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(image);

            img2.setIcon(icon);

        } catch (IOException ex) {
        }
        tit2.setText(p.getTitre());
        desc2.setText(p.getDescription());
        p = services.get(selected + 2);
        try {
            File sourceimage = new File(
                    LoginInfo.cwamp + LoginInfo.localhost + p.getImgServ());
            Image image = ImageIO.read(sourceimage).getScaledInstance(300, 200, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(image);

            img3.setIcon(icon);

        } catch (IOException ex) {
            
        }
        tit3.setText(p.getTitre());
        desc3.setText(p.getDescription());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(afficservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(afficservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(afficservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(afficservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new afficservice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea desc1;
    private javax.swing.JTextArea desc2;
    private javax.swing.JTextArea desc3;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel tit1;
    private javax.swing.JLabel tit2;
    private javax.swing.JLabel tit3;
    private javax.swing.JButton vd;
    private javax.swing.JButton vg;
    // End of variables declaration//GEN-END:variables
}
