/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Dao.CategorieProduitDao;
import Dao.ClientDao;
import Dao.ProduitDao;
import Entities.CategorieProduit;
import Entities.Client;
import Entities.Produit;
import Technique.Connexion;

import java.sql.Connection;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author Achref
 */
public class AjouterProduit extends javax.swing.JFrame {

   CategorieProduitDao cpd = new CategorieProduitDao();
    List<CategorieProduit> ListeCategorieProduit;

    /**
     * Creates new form AjouterProduit
     */
    public AjouterProduit() {
        initComponents();
         Statement ste;
    Connection connexion;
     ListeCategorieProduit = cpd.findAll();
        fillcombo();}
     public void fillcombo() {
        CategorieProduitDao cpd = new CategorieProduitDao();

        for (int i = 0; i < cpd.findAll().size(); i++) {

           CategorieProduitCombo.addItem(ListeCategorieProduit.get(i).getNom());
               }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DateFinDate = new com.toedter.calendar.JDateChooser();
        DescriptionTF = new javax.swing.JTextField();
        PublierBouton = new javax.swing.JButton();
        ResetAjout = new javax.swing.JButton();
        TitreTF = new javax.swing.JTextField();
        RetourAjout = new javax.swing.JButton();
        QuantiteTF = new javax.swing.JTextField();
        MarqueTF = new javax.swing.JTextField();
        PrixTF = new javax.swing.JTextField();
        CategorieProduitCombo = new javax.swing.JComboBox();
        ImageTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(DateFinDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 160, 30));
        getContentPane().add(DescriptionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 380, 176, 141));

        PublierBouton.setText("Publier");
        PublierBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublierBoutonActionPerformed(evt);
            }
        });
        getContentPane().add(PublierBouton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 640, 74, -1));

        ResetAjout.setText("Reinitialiser");
        ResetAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetAjoutActionPerformed(evt);
            }
        });
        getContentPane().add(ResetAjout, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 640, -1, -1));
        getContentPane().add(TitreTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 160, 30));

        RetourAjout.setText("<-Retour");
        RetourAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourAjoutActionPerformed(evt);
            }
        });
        getContentPane().add(RetourAjout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, -1, -1));
        getContentPane().add(QuantiteTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 220, 160, 30));

        MarqueTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarqueTFActionPerformed(evt);
            }
        });
        getContentPane().add(MarqueTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 160, 30));
        getContentPane().add(PrixTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, 160, 30));

        CategorieProduitCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategorieProduitComboActionPerformed(evt);
            }
        });
        getContentPane().add(CategorieProduitCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 160, 30));

        ImageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageTFActionPerformed(evt);
            }
        });
        getContentPane().add(ImageTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, 160, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userble.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 100, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btacceuilbleu.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btproduitbleu.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btserblanc.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btventeblanc.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blcontblan.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shopping-cart.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 60, -1, 50));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 130, 30));

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 130, 30));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 130, 30));

        jButton3.setText("jButton3");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 180, -1));

        jButton4.setText("jButton4");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 70, 110, 30));

        jButton5.setText("jButton5");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 80, 20, 10));

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 50, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/modproblanc.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gestprodbleu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gestserv.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, 80));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gvech.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        jButton11.setText("jButton8");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 213, 200, 50));

        jButton12.setText("jButton9");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 200, 50));

        jButton13.setText("jButton10");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 210, 50));

        jButton14.setText("jButton11");
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 543, 210, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/modprod.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ajouterprod.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/afficherprod.jpg"))); // NOI18N
        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, 30));

        jButton15.setText("jButton15");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 90, 30));

        jButton16.setText("jButton16");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 100, -1));

        jButton10.setText("jButton10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 90, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/produipubli.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PublierBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublierBoutonActionPerformed

            if(        !CategorieProduitCombo.getSelectedItem().equals("")

            && !MarqueTF.getText().equals("")
            && !PrixTF.getText().equals("")
                && !TitreTF.getText().equals("")
            && !DateFinDate.getDate().equals("")
            && !QuantiteTF.getText().equals("")
                && !ImageTF.getText().equals("")
                 && !DescriptionTF.getText().equals("")
                
              
                
        )
       { CategorieProduitDao cpd = new CategorieProduitDao();
            ClientDao cd = new ClientDao();
            Produit p = new Produit();
            Client c = new Client();
            p.setTitre(TitreTF.getText());
//            String xx=CategorieProduitCombo.getSelectedItem().toString();
//            System.out.println(xx);
//            if(xx.equals("hi-tech"))
//            {
//                System.out.println("wsel hne");
     //           p.setCategorie(cpd.findOne(1));
//            }
//           int choix=0 ;
//           if(CategorieProduitCombo.getSelectedItem().equals("hi_tech")){
//               choix=1;
//           }else if(CategorieProduitCombo.getSelectedItem().equals("Electromenager")){
//               choix = 2;
//           }else if(CategorieProduitCombo.getSelectedItem().equals("accesoires et lifestyle")){
//               choix = 3;
//           }else if(CategorieProduitCombo.getSelectedItem().equals("auto")){
//               choix = 4;
//           }
           
            p.setCategorie(cpd.findOne(CategorieProduitCombo.getSelectedIndex()));
           
           //p.setCategorie(cpd.findOne(choix));
           // p.setCategorie(CategorieProduitCombo.getSelectedItem().toString());
            p.setMarque(MarqueTF.getText());
            p.setPrix(Float.parseFloat(PrixTF.getText()));
            
            p.setDateFin(new java.sql.Date(DateFinDate.getDate().getYear(), DateFinDate.getDate().getMonth(), DateFinDate.getDate().getDay()));

            p.setQuantite(Integer.parseInt(QuantiteTF.getText()));
            
       
            p.setPict((ImageTF.getText()));
            p.setDescription(DescriptionTF.getText());
           
           
            

            ProduitDao pr = new ProduitDao();
            pr.ajouterProduit(p);
JOptionPane.showMessageDialog(null, "Produit ajouté avec succes", "Information", JOptionPane.INFORMATION_MESSAGE);

        }else{
            JOptionPane.showMessageDialog(null, "Veuillez Vérifier les champs svp", "Information", JOptionPane.INFORMATION_MESSAGE);

            
            
            
        }
       


    }//GEN-LAST:event_PublierBoutonActionPerformed

    private void ResetAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetAjoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetAjoutActionPerformed

    private void RetourAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourAjoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RetourAjoutActionPerformed

    private void MarqueTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarqueTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarqueTFActionPerformed

    private void CategorieProduitComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategorieProduitComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategorieProduitComboActionPerformed

    private void ImageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImageTFActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        homep p = new homep();
        p.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Produit pr = new Produit();
       // pr.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        afficservice as = new afficservice();
        as.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        AjouterService as = new AjouterService();
        as.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jLabel2AncestorAdded

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        AjouterProduit ap = new AjouterProduit();
        ap.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
//        ModifProduit mp = new ModifProduit();
//        mp.setVisible(true);
//        this.hide();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        AffichageProduit app = new AffichageProduit();
        app.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void ReinitialiserBActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        TitreTF.setText("");
        CategorieProduitCombo.setSelectedItem("");
        MarqueTF.setText("");
        PrixTF.setText("");
        DateFinDate.setDate(new java.sql.Date(DateFinDate.getDate().getYear(), DateFinDate.getDate().getMonth(), DateFinDate.getDate().getDay()));
        QuantiteTF.setText("");
        DescriptionTF.setText("");
        ImageTF.setText("");

    }

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold> 
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                   new AjouterProduit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CategorieProduitCombo;
    private com.toedter.calendar.JDateChooser DateFinDate;
    private javax.swing.JTextField DescriptionTF;
    private javax.swing.JTextField ImageTF;
    private javax.swing.JTextField MarqueTF;
    private javax.swing.JTextField PrixTF;
    private javax.swing.JButton PublierBouton;
    private javax.swing.JTextField QuantiteTF;
    private javax.swing.JButton ResetAjout;
    private javax.swing.JButton RetourAjout;
    private javax.swing.JTextField TitreTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
