/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Dao.ProduitDao;
import Dao.ServiceDao;
import Entities.Produit;
import Entities.Service;
import java.util.List;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author macbookpro
 */
public class DetailClient extends javax.swing.JFrame {

    int id_client;
    List<Service> listeService;
    List<Produit> listeProduit;

    /**
     * Creates new form DetailClient
     */
    public DetailClient(int id_client) {
        this.id_client = id_client;
        initComponents();
        updateTableProduit();
        updateTableService();
        recherche.setText("");
        recherche.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateTableProduit();
                updateTableService();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateTableProduit();
                updateTableService();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateTableProduit();
                updateTableService();
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableService = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableprod = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        recherche = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 718));
        setSize(new java.awt.Dimension(1, 1));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        updateTableService();
        jScrollPane1.setViewportView(tableService);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 200));

        tableprod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        updateTableProduit();
        jScrollPane2.setViewportView(tableprod);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, 200));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        back.setText("Retour");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, -1, -1));
        getContentPane().add(recherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 216, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/detcle.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        GestionClient JCon = new GestionClient();

        JCon.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    private void updateTableService() {

        ServiceDao sd = new ServiceDao();
        listeService = sd.findByClient(id_client);

        int i;
        int size = listeService.size();
        int j = 0;

        for (i = 0; i < size; i++) {
            if (!(listeService.get(j).getTitre().toLowerCase().contains(recherche.getText().toLowerCase())
                        || listeService.get(j).getCategorie().getNom().toLowerCase().contains(recherche.getText().toLowerCase())
                        || listeService.get(j).getCompetence().getNom().toLowerCase().contains(recherche.getText().toLowerCase())
                        || listeService.get(j).getClient().getFirstName().toLowerCase().contains(recherche.getText().toLowerCase())
                        || listeService.get(j).getClient().getLastName().toLowerCase().contains(recherche.getText().toLowerCase()))) {
                listeService.remove(listeService.get(j));

            } else {
                j++;
            }
        }
        if (listeService.size() > 0) {
            String[][] a = new String[listeService.size()][5];
            for (i = 0; i < listeService.size(); i++) {
                a[i][0] = listeService.get(i).getTitre();
                a[i][1] = listeService.get(i).getCategorie().getNom();
                a[i][2] = String.valueOf(listeService.get(i).getDate_fin());
                a[i][3] = listeService.get(i).getCompetence().getNom();
                a[i][4] = listeService.get(i).getClient().getLastName() + " " + listeService.get(i).getClient().getFirstName();

            }
            tableService.setModel(new javax.swing.table.DefaultTableModel(
                        a, new String[]{"Titre", "Categorie", "Date D'expiration", "Contre Service", "Client"}));
        } else {
            String[][] a = new String[0][2];
            tableService.setModel(new javax.swing.table.DefaultTableModel(
                        a, new String[]{"Titre", "Categorie", "Date D'expiration", "Contre Service", "Client"}));
        }

        tableService.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {

        });

    }

    private void updateTableProduit() {

        ProduitDao pd = new ProduitDao();
        listeProduit = pd.findByClient(id_client);
        int i;
        int size = listeProduit.size();
        int j = 0;

        for (i = 0; i < size; i++) {
            if (!(listeProduit.get(j).getTitre().toLowerCase().contains(recherche.getText().toLowerCase())
                        || listeProduit.get(j).getCategorie().getNom().toLowerCase().contains(recherche.getText().toLowerCase())
                        || listeProduit.get(j).getMarque().toLowerCase().contains(recherche.getText().toLowerCase())
                        || listeProduit.get(j).getClient().getFirstName().toLowerCase().contains(recherche.getText().toLowerCase())
                        || listeProduit.get(j).getClient().getLastName().toLowerCase().contains(recherche.getText().toLowerCase()))) {
                listeProduit.remove(listeProduit.get(j));
            } else {
                j++;
            }
        }
        if (listeProduit.size() > 0) {
            String[][] a = new String[listeProduit.size()][8];
            for (i = 0; i < listeProduit.size(); i++) {
                a[i][0] = listeProduit.get(i).getTitre();
                a[i][1] = listeProduit.get(i).getCategorie().getNom();
                a[i][3] = listeProduit.get(i).getMarque();
                a[i][4] = String.valueOf(listeProduit.get(i).getPrix());
                a[i][5] = String.valueOf(listeProduit.get(i).getDateFin());
                a[i][6] = String.valueOf(listeProduit.get(i).getQuantite());
                a[i][7] = listeProduit.get(i).getClient().getLastName() + " " + listeProduit.get(i).getClient().getFirstName();

            }
            tableprod.setModel(new javax.swing.table.DefaultTableModel(
                        a, new String[]{"Titre", "Categorie", "Marque", "Prix", "Date Expiration", "Quantite", "Client"}));
        } else {
            String[][] a = new String[0][2];
            tableprod.setModel(new javax.swing.table.DefaultTableModel(
                        a, new String[]{"Titre", "Categorie", "Marque", "Prix", "Date Expiration", "Quantite", "Client"}));
        }

        tableprod.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {

        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField recherche;
    private javax.swing.JTable tableService;
    private javax.swing.JTable tableprod;
    // End of variables declaration//GEN-END:variables
}
