/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Dao.PubliciteDao;
import Entities.Publicite;
import GUI.ListePub;
import java.awt.Image;
import java.io.BufferedInputStream;
import java.io.File;
import java.sql.Blob;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author lenovo i5
 */
public class GestPub extends javax.swing.JFrame {

    /**
     * Creates new form Publicité
     */
    
    static String p;
    
    public GestPub() {
        initComponents();
    }
    Publicite pub = new Publicite();
    PubliciteDao pdao = new PubliciteDao();
    ListePub lp=new ListePub();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browseField = new javax.swing.JLabel();
        Browse = new javax.swing.JButton();
        sauvegarder = new javax.swing.JButton();
        tfNom = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfDescription = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(browseField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 554, 161));

        Browse.setText("Parcourir publicité");
        Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseActionPerformed(evt);
            }
        });
        getContentPane().add(Browse, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        sauvegarder.setText("Sauvegarder");
        sauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauvegarderActionPerformed(evt);
            }
        });
        getContentPane().add(sauvegarder, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, 117, -1));
        getContentPane().add(tfNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 213, 30));

        tfDescription.setColumns(20);
        tfDescription.setRows(5);
        jScrollPane2.setViewportView(tfDescription);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 440, -1));

        jButton1.setText("Liste des publicitées");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gestionpubl.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser ch = new JFileChooser();
        ch.showOpenDialog(null);
        File f = ch.getSelectedFile();
        p= f.getAbsolutePath();
        pub.setPath(f.getAbsolutePath());
        ImageIcon ic = new ImageIcon(pub.getPath());
        Image img = ic.getImage().getScaledInstance(browseField.getWidth(), browseField.getHeight(), Image.SCALE_SMOOTH);
        browseField.setIcon(new ImageIcon(img));
        System.out.println(pub.getPath());
        
        
        
    }//GEN-LAST:event_BrowseActionPerformed

    private void sauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauvegarderActionPerformed
        // TODO add your handling code here:
        
        Publicite pub=new Publicite();
        PubliciteDao pubDao=new PubliciteDao();
        
        pub.setTitre(tfNom.getText());
        pub.setDescription(tfDescription.getText());
        pub.setPath(p);
        
        pubDao.ajouter(pub);
      
        lp.refresh();
      
        
        
    }//GEN-LAST:event_sauvegarderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
       
        
        lp.show();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Publicite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Publicite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Publicite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Publicite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new GestPub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Browse;
    private javax.swing.JLabel browseField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton sauvegarder;
    private javax.swing.JTextArea tfDescription;
    private javax.swing.JTextField tfNom;
    // End of variables declaration//GEN-END:variables
}
