/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import Dao.CategorieMereDao;
import Dao.CategorieProduitDao;
import Dao.CategorieServiceDao;
import Entities.CategorieMere;
import Entities.CategorieProduit;
import Entities.CategorieService;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.imageio.ImageIO;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saif Eddine
 */
public class GestionCategorie extends javax.swing.JFrame {

    /**
     * Creates new form GestionCategorie
     */
    CategorieMereDao cmd = new CategorieMereDao();
    List<CategorieMere> ListeCategorieMere;
    CategorieProduitDao cpd = new CategorieProduitDao();
    List<CategorieProduit> ListeCategorieProduit;
    CategorieServiceDao csd = new CategorieServiceDao();
    List<CategorieService> ListeCategorieService;

    public GestionCategorie() {

        initComponents();
        ListeCategorieMere = cmd.findAll();
        ListeCategorieProduit = cpd.findAll();
        ListeCategorieService = csd.findAll();
        fillcombo();
        AfficheCategorieService();
        AfficheCategorieProduit();
    }

    public void filltablep() {
        CategorieProduitDao cpd = new CategorieProduitDao();
        ListeCategorieProduit = cpd.findAll();
        for (int i = 0; i < cpd.findAll().size(); i++) {

            jTableCatP.setValueAt(ListeCategorieProduit.get(i).getNom(), i, 0);

        }
    }

    public void filltables() {

       
        for (int i = 0; i < csd.findAll().size(); i++) {

            jTabCatS.setValueAt(ListeCategorieService.get(i).getNom(), i, 0);

        }
    }

    public void fillcombo() {
        CategorieMereDao cmd = new CategorieMereDao();

        for (int i = 0; i < cmd.findAll().size(); i++) {

            CBCategorieMere.addItem(ListeCategorieMere.get(i).getNom());
            CBCategorieMere2.addItem(ListeCategorieMere.get(i).getNom());
        }
    }

    public void AfficheCategorieService() {
        
        DefaultTableModel models = (DefaultTableModel) jTabCatS.getModel();
        while (models.getRowCount() > 0) {
            for (int i = 0; i < models.getRowCount(); i++) {
                models.removeRow(i);
            }
        }
        DefaultTableModel model = (DefaultTableModel) jTabCatS.getModel();
        CategorieServiceDao csd = new CategorieServiceDao();
        Object[] rowData = new Object[1];
        for (int i = 0; i < csd.findAll().size(); i++) {
            rowData[0] = csd.findAll().get(i).getNom();
            model.addRow(rowData);

        }
        

    }

    public void AfficheCategorieProduit() {
            DefaultTableModel model = (DefaultTableModel) jTableCatP.getModel();
        while (model.getRowCount() > 0) {
            for (int i = 0; i < model.getRowCount(); i++) {
                model.removeRow(i);
            }
        }
        DefaultTableModel model1 = (DefaultTableModel) jTableCatP.getModel();
        CategorieProduitDao cpd = new CategorieProduitDao();
        Object[] rowData = new Object[1];
        if (CBCategorieMere2.getSelectedIndex() != -1) {
            int x = ListeCategorieMere.get(CBCategorieMere2.getSelectedIndex()).getId();
            for (int i = 0; i < cpd.RechercherCategorieProduitParCategorieMere(x).size(); i++) {
                rowData[0] = cpd.RechercherCategorieProduitParCategorieMere(x).get(i).getNom();
                model1.addRow(rowData);

            }

        }
    }

    private String groupButton1() {
        String radiotext = "";
        ButtonGroup bg = new ButtonGroup();

        bg.add(jRadioButton1);
        bg.add(jRadioButton3);
        if (bg.getSelection().equals(jRadioButton1.getModel())) {
            radiotext = "Categorie_Produit";

        } else if (bg.getSelection().equals(jRadioButton3.getModel())) {
            radiotext = "Categorie_Service";
        }
        return radiotext;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jexit = new javax.swing.JButton();
        CBCategorieMere2 = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCatP = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabCatS = new javax.swing.JTable();
        jsupprimers = new javax.swing.JButton();
        jsupprimerp = new javax.swing.JButton();
        jajouter = new javax.swing.JButton();
        jprecedent = new javax.swing.JButton();
        jTfNomCategorie = new javax.swing.JTextField();
        jTFNombrePoints = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        CBCategorieMere = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jexit.setText("Exit");
        jexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexitActionPerformed(evt);
            }
        });
        getContentPane().add(jexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 788, 109, 34));

        CBCategorieMere2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCategorieMere2ActionPerformed(evt);
            }
        });
        getContentPane().add(CBCategorieMere2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 125, 32));

        jTableCatP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categorie Produit"
            }
        ));
        jScrollPane1.setViewportView(jTableCatP);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 184, 211));

        jTabCatS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categorie Service"
            }
        ));
        jScrollPane2.setViewportView(jTabCatS);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 184, 211));

        jsupprimers.setText("Supprimer");
        jsupprimers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsupprimersActionPerformed(evt);
            }
        });
        getContentPane().add(jsupprimers, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 98, 35));

        jsupprimerp.setText("Supprimer");
        jsupprimerp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsupprimerpActionPerformed(evt);
            }
        });
        getContentPane().add(jsupprimerp, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 98, 35));

        jajouter.setText("Ajouter");
        jajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jajouterActionPerformed(evt);
            }
        });
        getContentPane().add(jajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 114, 31));

        jprecedent.setText("Precedent");
        jprecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jprecedentActionPerformed(evt);
            }
        });
        getContentPane().add(jprecedent, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, 100, 32));

        jTfNomCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfNomCategorieActionPerformed(evt);
            }
        });
        getContentPane().add(jTfNomCategorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 125, 32));

        jTFNombrePoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombrePointsActionPerformed(evt);
            }
        });
        getContentPane().add(jTFNombrePoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 125, 37));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Categorie Produit");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Categorie Service");
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        CBCategorieMere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCategorieMereActionPerformed(evt);
            }
        });
        getContentPane().add(CBCategorieMere, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 120, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/categorie.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jajouterActionPerformed
if (!"".equals(jTfNomCategorie.getText()) && !"".equals(jTFNombrePoints.getText()) )
{        String jBottonText = groupButton1();

        if ("Categorie_Produit".equals(jBottonText)) {
            CategorieProduit cp = new CategorieProduit();
            CategorieProduitDao cpd = new CategorieProduitDao();
            cp.setNom(jTfNomCategorie.getText());
            cp.setNbPts(Integer.parseInt(jTFNombrePoints.getText()));
            cp.setCategorieMere(ListeCategorieMere.get(CBCategorieMere.getSelectedIndex()));
            cpd.ajouterCategorieProduit(cp);
        } else if ("Categorie_Service".equals(jBottonText)) {
            CategorieService cs = new CategorieService();
            CategorieServiceDao csd = new CategorieServiceDao();
            cs.setNom(jTfNomCategorie.getText());
            cs.setNbPts(Integer.parseInt(jTFNombrePoints.getText()));

            csd.ajouterCategorieService(cs);
        }

  
          DefaultTableModel modelp = (DefaultTableModel) jTabCatS.getModel();
        while (modelp.getRowCount() > 0) {
            for (int i = 0; i < modelp.getRowCount(); i++) {
                modelp.removeRow(i);
            }
        }
AfficheCategorieService();
AfficheCategorieProduit();
    }//GEN-LAST:event_jajouterActionPerformed
    else
{
  JOptionPane.showMessageDialog(null, "Vérifier votre saisie", "Information", JOptionPane.INFORMATION_MESSAGE);
}
    
    
    }
    private void jexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexitActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_jexitActionPerformed

    private void jprecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jprecedentActionPerformed

//        hopage h = null;
//        try {
//            h = new hopage();
//        } 
//        catch (IOException ex) {
//            Logger.getLogger(GestionCategorie1.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        h.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_jprecedentActionPerformed


    private void jsupprimersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsupprimersActionPerformed

        CategorieServiceDao csd = new CategorieServiceDao();
        System.out.println(jTabCatS.getSelectedRow());
        csd.supprimerCategorieService(ListeCategorieService.get(jTabCatS.getSelectedRow()));
        JOptionPane.showMessageDialog(null, "Categorie Supprimée", "Information", JOptionPane.INFORMATION_MESSAGE);
        DefaultTableModel model = (DefaultTableModel) jTabCatS.getModel();
        while (model.getRowCount() > 0) {
            for (int i = 0; i < model.getRowCount(); i++) {
                model.removeRow(i);
            }
        }
        AfficheCategorieService();
    }//GEN-LAST:event_jsupprimersActionPerformed

    private void jsupprimerpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsupprimerpActionPerformed
        
        ListeCategorieProduit = cpd.findAll();  
        CategorieProduit cp = new CategorieProduit();
        CategorieProduitDao cpd = new CategorieProduitDao();
        cpd.supprimerCategorieProduit(ListeCategorieProduit.get(jTableCatP.getSelectedRow()));
        JOptionPane.showMessageDialog(null, "Categorie Supprimée", "Information", JOptionPane.INFORMATION_MESSAGE);
        DefaultTableModel model = (DefaultTableModel) jTableCatP.getModel();
        while (model.getRowCount() > 0) {
            for (int i = 0; i < model.getRowCount(); i++) {
                model.removeRow(i);
            }
        }
        AfficheCategorieProduit();

    }//GEN-LAST:event_jsupprimerpActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed


    private void CBCategorieMereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCategorieMereActionPerformed
//       CBCategorieMere.addItem(cmd.Fillcombo());


    }//GEN-LAST:event_CBCategorieMereActionPerformed

    private void jTFNombrePointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombrePointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombrePointsActionPerformed

    private void CBCategorieMere2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCategorieMere2ActionPerformed
        AfficheCategorieService();
        AfficheCategorieProduit();
    }//GEN-LAST:event_CBCategorieMere2ActionPerformed

    private void jTfNomCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfNomCategorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfNomCategorieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionCategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionCategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionCategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionCategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionCategorie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBCategorieMere;
    private javax.swing.JComboBox<String> CBCategorieMere2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFNombrePoints;
    private javax.swing.JTable jTabCatS;
    private javax.swing.JTable jTableCatP;
    private javax.swing.JTextField jTfNomCategorie;
    private javax.swing.JButton jajouter;
    private javax.swing.JButton jexit;
    private javax.swing.JButton jprecedent;
    private javax.swing.JButton jsupprimerp;
    private javax.swing.JButton jsupprimers;
    // End of variables declaration//GEN-END:variables
}
