/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Dao.ClientDao;
import Dao.ProduitDao;
import Entities.Client;
import Entities.Produit;

import java.util.List;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author macbookpro
 */
public class GestionProduitAdmin extends javax.swing.JFrame {

    List<Produit> listeProduit;

    /**
     * Creates new form GestionClient
     */
    public GestionProduitAdmin() {
        initComponents();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                null, new String[]{"titre", "Categorie", "marque", "prix", "duree produit", "quantité", "Etat", "Vendu", "Proprietaire"}));
        updateTableProduit();
        recherche.setText("");
        recherche.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateTableProduit();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateTableProduit();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateTableProduit();
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        retour = new javax.swing.JButton();
        recherche = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ProduitId = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        updateTableProduit();
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 700, 180));

        retour.setText("Retour");
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });
        getContentPane().add(retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 540, 110, 30));

        recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheActionPerformed(evt);
            }
        });
        getContentPane().add(recherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 160, 30));

        jButton2.setText("Effacer Produit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 550, 135, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Gc.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, -1, -1));

        ProduitId.setText("jLabel1");
        getContentPane().add(ProduitId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheActionPerformed

    }//GEN-LAST:event_rechercheActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        ProduitDao pd = new ProduitDao();
        Produit p = listeProduit.get(jTable1.getSelectedRow());
        pd.supprimerProduit(p);
        listeProduit.remove(p);
        updateTableProduit();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
        AdminInterface cg = new AdminInterface();
       cg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_retourActionPerformed

    /**
     * @param args the command line arguments
     */
    private void updateTableProduit() {

        ProduitDao pr = new ProduitDao();
        listeProduit = pr.findAll();

        int i;
        int size = listeProduit.size();
        int j = 0;
        for (i = 0; i < size; i++) {
            if (!(listeProduit.get(j).getTitre().toLowerCase().contains(recherche.getText().toLowerCase())
                    || listeProduit.get(j).getCategorie().getNom().toLowerCase().contains(recherche.getText().toLowerCase())
                    || listeProduit.get(j).getMarque().toLowerCase().contains(recherche.getText().toLowerCase())
                    || listeProduit.get(j).getClient().getFirstName().toLowerCase().contains(recherche.getText().toLowerCase())
                    || listeProduit.get(j).getClient().getLastName().toLowerCase().contains(recherche.getText().toLowerCase()))) {
                listeProduit.remove(listeProduit.get(j));
            } else {
                j++;
            }
        }

        for (i = 0; i < size; i++) {
            if (listeProduit.size() > 0) {

                String[][] p = new String[listeProduit.size()][9];
                for (i = 0; i < listeProduit.size(); i++) {
                    p[i][0] = listeProduit.get(i).getTitre();
                    p[i][1] = listeProduit.get(i).getCategorie().getNom();
                    p[i][2] = listeProduit.get(i).getMarque();
                    p[i][3] = String.valueOf(listeProduit.get(i).getPrix());

                    p[i][4] = String.valueOf(listeProduit.get(i).getDateFin());
                    p[i][5] = String.valueOf(listeProduit.get(i).getQuantite());
                    p[i][6] = String.valueOf(listeProduit.get(i).getEstValide());
                    p[i][7] = String.valueOf(listeProduit.get(i).getEstAchetee());

                    p[i][8] = listeProduit.get(i).getClient().getFirstName() + " " + listeProduit.get(i).getClient().getLastName();

                }
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        p, new String[]{"titre", "Categorie", "marque", "prix", "duree produit", "quantité", "Etat", "Vendu", "Proprietaire"}));
            } else {
                String[][] p = new String[0][2];
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        p, new String[]{"titre", "Categorie", "marque", "prix", "duree produit", "quantité", "Etat", "Vendu", "Proprietaire"}));
            }
        }
        jTable1.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {

        });

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionProduitAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionProduitAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionProduitAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionProduitAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GestionProduitAdmin().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProduitId;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField recherche;
    private javax.swing.JButton retour;
    // End of variables declaration//GEN-END:variables
}
