/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entities.Client;
import Interfaces.IClient;
import Dao.ClientDao;
import Dao.PanierDao;
import Dao.ProduitDao;
import Dao.SendEmailDao;
import Entities.MAIL;
import Entities.Panier;
import Entities.Produit;
import static GUI.connection.NL;
import Technique.Connexion;
import java.awt.Dimension;
import java.awt.GraphicsConfiguration;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import javafx.scene.control.ComboBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
//import javax.swing.JOptionPane;

/**
 *
 * @author AZIZ
 */
public class inscriptionpage extends javax.swing.JFrame {

    ///MAIL///
    public static final String NL = System.getProperty("line.separator");
    SendEmailDao mail = new SendEmailDao();
    MAIL mail_client = new MAIL();
/////////////Entity////////////////////
    Client client;
    Panier panier = new Panier();
    Produit produit = new Produit();
///////////////////DAO/////////////////
    PanierDao p = new PanierDao();
    ProduitDao x = new ProduitDao();
    ClientDao c = new ClientDao();
            /////////////////////////////////

    public inscriptionpage(GraphicsConfiguration gc) {
        super(gc);
    }

    /**
     * Creates new form inscriptionpage
     */
    public inscriptionpage() {
        initComponents();
        client = new Client();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_echec = new javax.swing.JOptionPane();
        dialog_succes = new javax.swing.JOptionPane();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        adresse = new javax.swing.JTextField();
        sexe = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        btnIsncription = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 140, 30));

        prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomActionPerformed(evt);
            }
        });
        getContentPane().add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 140, 30));
        getContentPane().add(telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 140, 30));
        getContentPane().add(adresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 140, 30));

        sexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "homme", "femme" }));
        sexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexeActionPerformed(evt);
            }
        });
        getContentPane().add(sexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/en.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));

        btnIsncription.setText("Inscription");
        btnIsncription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIsncriptionActionPerformed(evt);
            }
        });
        getContentPane().add(btnIsncription, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 483, 120, 30));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 140, 30));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 140, 30));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 140, 30));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 140, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1_3.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomActionPerformed

    private void sexeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexeActionPerformed

    private void btnIsncriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsncriptionActionPerformed
        // TODO add your handling code here:

        client.setLastName(nom.getText());

        client.setFirstName(prenom.getText());
        int xt = Integer.parseInt(telephone.getText());
        client.setTelephone(xt);

        client.setAdresse(adresse.getText());
        // date naissance 
        java.sql.Date date_naiss = new java.sql.Date(jDateChooser1.getDate().getTime());
        client.setDateNaissance(date_naiss);
//        client.setAdresse(tf_adresse.getText());

        client.setEmail(email.getText());

        client.setUsername(username.getText());

        client.setPassword(password.getText());
//        client.setCurrent_system(System.getProperty("os.name"));
//        client.setCompetence(tf_competence.getText());
        if (((String) sexe.getSelectedItem()) == "homme") {
            client.setSexe(1);
        } else {
            client.setSexe(0);
        }

        /*IClient client = new ClientDao();*/
        if (!"".equals(nom.getText()) && !"".equals(prenom.getText())) {

            
            c.ajouterClient(client, password.getText());

            String login = username.getText();
            String pass = password.getText();
            String mail_c = email.getText();

            mail_client.setMail_client(mail_c);
            mail_client.setContenu("Cher Client," + NL + NL
                    + " l'équipe All For Deal vous souhaite la bienvenue !" + NL
                    + "On souhaite également vous informer de vos paramètre de connexion" + NL + NL
                    + "votre login est : " + login + NL
                    + "votre mot de passe est : " + pass + NL + NL
                    + "Rendez-vous sur l'application si vous souhaitez changer de mot de passe" + NL + NL + NL + NL
                    + "L'équipe ALL FOR DEAL");
            mail_client.setSubject("Bienvenu");
            mail.send2_client(mail_client);
            dialog_succes.showMessageDialog(null, "Utilisateur Ajouté", "Information", JOptionPane.INFORMATION_MESSAGE);
            connection JCon = new connection();
            JCon.setVisible(true);
            dispose();

        } else {
            dialog_echec.showMessageDialog(null, "Un ou plusieurs champs sont vides", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        //JOptionPane.showMessageDialog(null,"employé");
        /*home h= new home();
         h.setVisible(true);
         this.hide();*/

        /* IDepotDao depotDao = new DepotDao();
         depotDao.addDepot(depot);*/

    }//GEN-LAST:event_btnIsncriptionActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inscriptionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inscriptionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inscriptionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inscriptionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inscriptionpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresse;
    private javax.swing.JButton btnIsncription;
    private javax.swing.JOptionPane dialog_echec;
    private javax.swing.JOptionPane dialog_succes;
    private javax.swing.JTextField email;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField password;
    private javax.swing.JTextField prenom;
    private javax.swing.JComboBox sexe;
    private javax.swing.JTextField telephone;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
