/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Dao.ProduitDao;
import Dao.ServiceDao;
import Entities.Produit;
import Entities.Service;
import Technique.Connexion;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Achref
 */
public class ModifProduit extends javax.swing.JFrame {

    ProduitDao sd = new ProduitDao();

    List<Produit> ListeProduits = sd.findAll();
    public Connection conn = Connexion.getIstanceConnexion();
    private Object connexion;
    private int id;

    /**
     * Creates new form ModifProduit
     */
    public ModifProduit() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CategorieProduitComboModif = new javax.swing.JComboBox();
        MarqueModif = new javax.swing.JTextField();
        DateFinModif = new com.toedter.calendar.JDateChooser();
        PrixModif = new javax.swing.JTextField();
        DescriptionModif = new javax.swing.JTextField();
        ImageModif = new javax.swing.JTextField();
        QuantiteModif = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        TitreModifier = new javax.swing.JTextField();
        idd = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CategorieProduitComboModif.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "hi-tech", "Electromenager", "accesoires et lifestyle", "auto" }));
        CategorieProduitComboModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategorieProduitComboModifActionPerformed(evt);
            }
        });
        getContentPane().add(CategorieProduitComboModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, 30));

        MarqueModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarqueModifActionPerformed(evt);
            }
        });
        getContentPane().add(MarqueModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 128, 30));

        DateFinModif.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(DateFinModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 128, 30));
        getContentPane().add(PrixModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 128, 30));

        DescriptionModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionModifActionPerformed(evt);
            }
        });
        getContentPane().add(DescriptionModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 390, 300, 110));
        getContentPane().add(ImageModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 310, 128, 30));
        getContentPane().add(QuantiteModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 230, 128, 30));

        jButton1.setText("retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, -1, -1));

        jButton2.setText("enregister modification");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 600, -1, -1));

        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 120, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userble.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 100, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btacceuilbleu.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btproduitbleu.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btserblanc.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btventeblanc.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blcontblan.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shopping-cart.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 60, -1, 50));

        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 130, 30));

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 130, 30));

        jButton4.setText("jButton2");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 130, 30));

        jButton5.setText("jButton3");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 180, -1));

        jButton6.setText("jButton4");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 70, 110, 30));

        jButton8.setText("jButton5");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 80, 20, 10));

        jButton9.setText("jButton6");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 50, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/modproblanc.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gestprodbleu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gestserv.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, 80));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gvech.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, 70));

        jButton11.setText("jButton8");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 213, 200, 50));

        jButton12.setText("jButton9");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 200, 50));

        jButton13.setText("jButton10");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 210, 50));

        jButton14.setText("jButton11");
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 210, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ajouterprod.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/modprod.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/afficherprod.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, 30));

        jButton10.setText("jButton10");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jButton15.setText("jButton15");
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        jButton16.setText("jButton16");
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));
        getContentPane().add(TitreModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 120, -1));
        getContentPane().add(idd, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 40, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/modiproduiajo.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CategorieProduitComboModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategorieProduitComboModifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategorieProduitComboModifActionPerformed

    private void MarqueModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarqueModifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarqueModifActionPerformed

    private void DescriptionModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionModifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionModifActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(  
             !MarqueModif.getText().equals("")
            && !PrixModif.getText().equals("")
                && !TitreModifier.getText().equals("")
            && !DateFinModif.getDate().equals("")
            && !QuantiteModif.getText().equals("")
            //    && !ImageModif.getText().equals("")
                 && !DescriptionModif.getText().equals("")){
        Produit p = new Produit();
       //p.setId(Integer.parseInt(id.getText()));
       p.setTitre(TitreModifier.getText());
       p.setMarque(MarqueModif.getText());
       p.setQuantite(Integer.parseInt(QuantiteModif.getText()));
       p.setPrix(Float.parseFloat(PrixModif.getText()));
       p.setDateFin(new java.sql.Date(DateFinModif.getDate().getTime()));
       p.setDescription(DescriptionModif.getText());
       p.setPict("fezsdxcv");
       new ProduitDao().modifierProduit(p);
       JOptionPane.showMessageDialog(null, "Modification Effectuée Avec Succès", "Information", JOptionPane.INFORMATION_MESSAGE);
     
       }
       else{ 
           JOptionPane.showMessageDialog(null, "Veuillez Vérifier les champs svp", "Information", JOptionPane.INFORMATION_MESSAGE);
       }

       
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        homep p = new homep();
        p.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         GUI.Produit pr = new GUI.Produit();
        pr.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        afficservice as = new afficservice();
        as.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
AffichageProduit ap = new AffichageProduit();
this.hide();
 ap.show();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifierService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifierService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifierService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifierService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
//                ClientDao cd = new ClientDao();
//                LoginInfo.setClient(cd.findOne(8));
                new ModifProduit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JComboBox CategorieProduitComboModif;
    protected com.toedter.calendar.JDateChooser DateFinModif;
    protected javax.swing.JTextField DescriptionModif;
    protected javax.swing.JTextField ImageModif;
    protected javax.swing.JTextField MarqueModif;
    protected javax.swing.JTextField PrixModif;
    protected javax.swing.JTextField QuantiteModif;
    public javax.swing.JTextField TitreModifier;
    public javax.swing.JLabel idd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
